Medicina/Models/Historicoes.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Medicina.Models
{
    public partial class Historicoes
    {
        public int HistoricoId { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }

        [Display(Name = "Identificacion")]
        public string NumeroIdentificacion { get; set; }

        [Display(Name = "Antecendes Personales")]
        public string AntecendesPersonales { get; set; }

        [Display(Name = "Motivo de consulta")]
        public string MotivoConsulta { get; set; }

        [Display(Name = "Examen físico")]
        public string ExamenFisico { get; set; }

        [Display(Name = "Tratamientos o estudios")]
        public string TratamientosOEstudios { get; set; }

        [Display(Name = "Resultado de Laboratorio")]
        public string ResultadoLaboratorio { get; set; }

        [Display(Name = "Identificacion")]
        public string Indicaciones { get; set; }

        [Display(Name = "Fecha de hoy")]
        public DateTime FechaHoy { get; set; }

        [Display(Name = "Fecha para volver")]
        public DateTime? FechaVolver { get; set; }

        [Display(Name = "Fecha de primera vez")]
        public DateTime? FechaPrimeraVez { get; set; }
    }
}

Medicina/Controllers/HistoricoesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Medicina.Models;

namespace Medicina.Controllers
{
    public class HistoricoesController : Controller
    {
        private readonly EasyMedicineContext _context;

        public HistoricoesController(EasyMedicineContext context)
        {
            _context = context;
        }

        // GET: Historicoes
        public async Task<IActionResult> Index()
        {
            return View(await _context.Historicoes.ToListAsync());
        }

        // GET: Historicoes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var historicoes = await _context.Historicoes
                .SingleOrDefaultAsync(m => m.HistoricoId == id);
            if (historicoes == null)
            {
                return NotFound();
            }

            return View(historicoes);
        }

        // GET: Historicoes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Historicoes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("HistoricoId,Nombre,Apellido,NumeroIdentificacion,AntecendesPersonales,MotivoConsulta,ExamenFisico,TratamientosOEstudios,ResultadoLaboratorio,Indicaciones,FechaHoy,FechaVolver,FechaPrimeraVez")] Historicoes historicoes)
        {
            if (ModelState.IsValid)
            {
                _context.Add(historicoes);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(historicoes);
        }

        // GET: Historicoes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var historicoes = await _context.Historicoes.SingleOrDefaultAsync(m => m.HistoricoId == id);
            if (historicoes == null)
            {
                return NotFound();
            }
            return View(historicoes);
        }

        // POST: Historicoes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("HistoricoId,Nombre,Apellido,NumeroIdentificacion,AntecendesPersonales,MotivoConsulta,ExamenFisico,TratamientosOEstudios,ResultadoLaboratorio,Indicaciones,FechaHoy,FechaVolver,FechaPrimeraVez")] Historicoes historicoes)
        {
            if (id != historicoes.HistoricoId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(historicoes);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!HistoricoesExists(historicoes.HistoricoId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(historicoes);
        }

        public ActionResult Consulta(string Numero_Identificacion)
        {
            var pas = _context.Historicoes .OrderByDescending(c => c.HistoricoId)
                .Where(c => c.NumeroIdentificacion == Numero_Identificacion).ToList();

            if (pas.Count() == 0)
            {
                ViewBag.error = "El número de identificación no es valido";
                return View(pas);
            }
            else
                return View(pas);   
        }

        // GET: Historicoes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var historicoes = await _context.Historicoes
                .SingleOrDefaultAsync(m => m.HistoricoId == id);
            if (historicoes == null)
            {
                return NotFound();
            }

            return View(historicoes);
        }

        // POST: Historicoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var historicoes = await _context.Historicoes.SingleOrDefaultAsync(m => m.HistoricoId == id);
            _context.Historicoes.Remove(historicoes);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool HistoricoesExists(int id)
        {
            return _context.Historicoes.Any(e => e.HistoricoId == id);
        }
    }
}

Medicina/Views/Historicoes/Consulta.cshtml
@model IEnumerable<Medicina.Models.Historicoes>

@{
    ViewData["Title"] = "Consultas de pacientes";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@*<h2>Consulta</h2>*@

@using (Html.BeginForm("consulta", "Historicoes", FormMethod.Get))
{
    <p>
        Busqueda por No. de Identificacion: @Html.TextBox("Numero_Identificacion", "", new { @class = "form-control" }) <br />
        @ViewBag.error <br />
        <input type="submit" value="Buscar" class="btn btn-info" />
    </p>
}

<div class="table-responsive">
    <table class="table">
        <thead class="text-primary">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Nombre)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Apellido)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.NumeroIdentificacion)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.AntecendesPersonales)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.MotivoConsulta)
                </th>
                @* <th>
            @Html.DisplayNameFor(model => model.ExamenFisico)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TratamientosOEstudios)
        </th>
        <th>
                @Html.DisplayNameFor(model => model.ResultadoLaboratorio)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Indicaciones)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaHoy)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaVolver)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaPrimeraVez)
            </th>*@
                <th></th>
            </tr>
        </thead>

        <tbody>
            @foreach (var item in Model)
            {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Apellido)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NumeroIdentificacion)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.AntecendesPersonales)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.MotivoConsulta)
                </td>
                @*<td>
            @Html.DisplayFor(modelItem => item.ExamenFisico)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TratamientosOEstudios)
        </td>
        <td>
                @Html.DisplayFor(modelItem => item.ResultadoLaboratorio)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Indicaciones)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FechaHoy)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FechaVolver)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FechaPrimeraVez)
            </td>*@
                <td>
                    <a asp-action="Edit" asp-route-id="@item.HistoricoId">Editar</a> |
                    <a asp-action="Details" asp-route-id="@item.HistoricoId">Detalles</a> |
                    <a asp-action="Delete" asp-route-id="@item.HistoricoId">Eliminar</a>
                </td>
            </tr>
            }
        </tbody>
    </table>
</div>

Medicina/Views/Historicoes/Create.cshtml
@model Medicina.Models.Historicoes

@{
    ViewData["Title"] = "Crear nuevo historico";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<hr />

<form asp-action="Create">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="row">
        <div class="col-md-4">
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                <label asp-for="Apellido" class="control-label"></label>
                <input asp-for="Apellido" class="form-control" />
                <span asp-validation-for="Apellido" class="text-danger"></span>
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                <label asp-for="NumeroIdentificacion" class="control-label"></label>
                <input asp-for="NumeroIdentificacion" class="form-control" />
                <span asp-validation-for="NumeroIdentificacion" class="text-danger"></span>
            </div>
        </div>
    
    </div>
    <div class="row">
        <div class="col-md-4">
            <div class="form-group">
                <label asp-for="AntecendesPersonales" class="control-label"></label>
                <input asp-for="AntecendesPersonales" class="form-control" />
                <span asp-validation-for="AntecendesPersonales" class="text-danger"></span>
            </div>
        </div>

        <div class="col-md-4">
            <div class="form-group">
                <label asp-for="MotivoConsulta" class="control-label"></label>
                <input asp-for="MotivoConsulta" class="form-control" />
                <span asp-validation-for="MotivoConsulta" class="text-danger"></span>
            </div>
        </div>

            <div class="col-md-4">
                <div class="form-group">
                    <label asp-for="ExamenFisico" class="control-label"></label>
                    <input asp-for="ExamenFisico" class="form-control" />
                    <span asp-validation-for="ExamenFisico" class="text-danger"></span>
                </div>
            </div>
        </div>
    <div class="row">
        <div class="col-md-4">
            <div class="form-group">
                <label asp-for="TratamientosOEstudios" class="control-label"></label>
                <input asp-for="TratamientosOEstudios" class="form-control" />
                <span asp-validation-for="TratamientosOEstudios" class="text-danger"></span>
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                <label asp-for="ResultadoLaboratorio" class="control-label"></label>
                <input asp-for="ResultadoLaboratorio" class="form-control" />
                <span asp-validation-for="ResultadoLaboratorio" class="text-danger"></span>
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                <label asp-for="Indicaciones" class="control-label"></label>
                <input asp-for="Indicaciones" class="form-control" />
                <span asp-validation-for="Indicaciones" class="text-danger"></span>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            <div class="form-group">
                <label asp-for="FechaHoy" class="control-label"></label>
                <input asp-for="FechaHoy" class="form-control" />
                <span asp-validation-for="FechaHoy" class="text-danger"></span>
            </div>
        </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label asp-for="FechaVolver" class="control-label"></label>
                    <input asp-for="FechaVolver" class="form-control" />
                    <span asp-validation-for="FechaVolver" class="text-danger"></span>
                </div>
            </div>

                <div class="col-md-4">
                    <div class="form-group">
                        <label asp-for="FechaPrimeraVez" class="control-label"></label>
                        <input asp-for="FechaPrimeraVez" class="form-control" />
                        <span asp-validation-for="FechaPrimeraVez" class="text-danger"></span>
                    </div>
                </div>
            </div>
    <div class="row">
        <div class="col-md-4">
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>


<div>
    <a asp-action="Index">Volver atrás</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Medicina/Views/Historicoes/Delete.cshtml
@model Medicina.Models.Historicoes

@{
    ViewData["Title"] = "Eliminar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h3>Desea eliminar el siguiente historico?</h3>
<div>

    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Apellido)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Apellido)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.NumeroIdentificacion)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.NumeroIdentificacion)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.AntecendesPersonales)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.AntecendesPersonales)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.MotivoConsulta)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.MotivoConsulta)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ExamenFisico)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ExamenFisico)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.TratamientosOEstudios)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TratamientosOEstudios)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ResultadoLaboratorio)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ResultadoLaboratorio)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Indicaciones)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Indicaciones)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.FechaHoy)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FechaHoy)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.FechaVolver)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FechaVolver)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.FechaPrimeraVez)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FechaPrimeraVez)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="HistoricoId" />
        <input type="submit" value="Eliminar" class="btn btn-default" /> |
        <a asp-action="Index">Volver atrás</a>
    </form>
</div>

Medicina/Views/Historicoes/Details.cshtml
@model Medicina.Models.Historicoes

@{
    ViewData["Title"] = "Detalles";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div>

    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Apellido)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Apellido)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.NumeroIdentificacion)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.NumeroIdentificacion)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.AntecendesPersonales)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.AntecendesPersonales)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.MotivoConsulta)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.MotivoConsulta)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ExamenFisico)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ExamenFisico)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.TratamientosOEstudios)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TratamientosOEstudios)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ResultadoLaboratorio)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ResultadoLaboratorio)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Indicaciones)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Indicaciones)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.FechaHoy)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FechaHoy)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.FechaVolver)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FechaVolver)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.FechaPrimeraVez)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FechaPrimeraVez)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.HistoricoId">Editar</a> |
    <a asp-action="Index">Volver atrás</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Medicina/Views/Historicoes/Edit.cshtml
@model Medicina.Models.Historicoes

@{
    ViewData["Title"] = "Editar historico";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="HistoricoId" />
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Apellido" class="control-label"></label>
                <input asp-for="Apellido" class="form-control" />
                <span asp-validation-for="Apellido" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumeroIdentificacion" class="control-label"></label>
                <input asp-for="NumeroIdentificacion" class="form-control" />
                <span asp-validation-for="NumeroIdentificacion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AntecendesPersonales" class="control-label"></label>
                <input asp-for="AntecendesPersonales" class="form-control" />
                <span asp-validation-for="AntecendesPersonales" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MotivoConsulta" class="control-label"></label>
                <input asp-for="MotivoConsulta" class="form-control" />
                <span asp-validation-for="MotivoConsulta" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ExamenFisico" class="control-label"></label>
                <input asp-for="ExamenFisico" class="form-control" />
                <span asp-validation-for="ExamenFisico" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TratamientosOEstudios" class="control-label"></label>
                <input asp-for="TratamientosOEstudios" class="form-control" />
                <span asp-validation-for="TratamientosOEstudios" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ResultadoLaboratorio" class="control-label"></label>
                <input asp-for="ResultadoLaboratorio" class="form-control" />
                <span asp-validation-for="ResultadoLaboratorio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Indicaciones" class="control-label"></label>
                <input asp-for="Indicaciones" class="form-control" />
                <span asp-validation-for="Indicaciones" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaHoy" class="control-label"></label>
                <input asp-for="FechaHoy" class="form-control" />
                <span asp-validation-for="FechaHoy" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaVolver" class="control-label"></label>
                <input asp-for="FechaVolver" class="form-control" />
                <span asp-validation-for="FechaVolver" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaPrimeraVez" class="control-label"></label>
                <input asp-for="FechaPrimeraVez" class="form-control" />
                <span asp-validation-for="FechaPrimeraVez" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Volver atrás</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Medicina/Views/Historicoes/Index.cshtml
@model IEnumerable<Medicina.Models.Historicoes>

@{
    ViewData["Title"] = "Historico de pacientes";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<p>
    <a asp-action="Create">Crear nuevo historico</a>
</p>

@using (Html.BeginForm("consulta", "Historicoes", FormMethod.Get))
{
    <p>
        Busqueda por No. de Identificacion: @Html.TextBox("Numero_Identificacion", "", new { @class = "form-control" }) <br />
        @ViewBag.error <br />
        <input type="submit" value="Buscar" class="btn btn-info" />
    </p>
}

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Apellido)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NumeroIdentificacion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AntecendesPersonales)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MotivoConsulta)
            </th>
            @*<th>
                @Html.DisplayNameFor(model => model.ExamenFisico)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TratamientosOEstudios)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ResultadoLaboratorio)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Indicaciones)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaHoy)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaVolver)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaPrimeraVez)
            </th>*@
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Apellido)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NumeroIdentificacion)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.AntecendesPersonales)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.MotivoConsulta)
                </td>
                @*<td>
                    @Html.DisplayFor(modelItem => item.ExamenFisico)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TratamientosOEstudios)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ResultadoLaboratorio)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Indicaciones)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FechaHoy)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FechaVolver)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FechaPrimeraVez)
                </td>*@
                <td>
                    <a asp-action="Edit" asp-route-id="@item.HistoricoId">Editar</a> |
                    <a asp-action="Details" asp-route-id="@item.HistoricoId">Detalles</a> |
                    <a asp-action="Delete" asp-route-id="@item.HistoricoId">Eliminar</a>
                </td>
            </tr>
        }
    </tbody>
</table>